### Multiple Linear Regression
y = $\beta_l$ X1 + $\beta_l$ X2 + .... + $\beta_l$ Xn + $\beta_0$ + $\epsilon$

**Mutiple Linear Regression for final scores** <br>

y(Final Score) = $\beta_l$(hours_studied) + $\beta_l$(IQ) + $\beta_l$(attendance) + $\beta_0$ + $\epsilon$ <br>

y = 6(hours_studied) + 2(IQ) + 3(attendance) + 30

In [6]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

df = pd.DataFrame({
    "Hours_studied": np.random.rand(100) * 20,
    "Attendance": np.random.rand(100) * 5,
    "IQ": np.random.rand(100) * 80+ 80,
    "final_score": np.random.rand(100) * 100
})
df.head()

   Hours_studied  Attendance          IQ  final_score
0       4.256090    2.318829  101.857381    36.414093
1      10.283834    3.644074  127.947941    79.480465
2      12.607163    0.755467  138.204427    32.021458
3      17.571143    2.671834  146.175294    69.911522
4      12.754307    2.426180   88.460662    36.477729

In [7]:
# Save the dataframe to a CSV file
df.to_csv("student_data.csv", index=False)

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

# Load the data from the CSV file
df = pd.read_csv("student_data.csv")

# Select the features and target variable
X = df[["Hours_studied", "Attendance", "IQ"]]
y = df["final_score"]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and fit the linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

df_y_pred_y_test = pd.DataFrame({
    "y_pred": y_pred,
    "y_test": y_test
})
df_y_pred_y_test.head()

       y_pred     y_test
83  37.160107  87.867433
53  33.862271  33.427411
70  39.675886  89.437453
45  49.531200  28.454479
44  46.604409  19.627095

In [10]:
# The metrics
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")
print(f"Mean Absolute Error: {mae}")

Mean Squared Error: 745.7768972106878
R-squared: -0.09279730365485372
Mean Absolute Error: 22.848613555116096

In [11]:
# Model Summary
print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)

Coefficients: [-0.25965177  5.67371283 -0.02472619]
Intercept: 38.115506895169986