In [1]:
import pandas as pd
import sqlite3

conn = sqlite3.connect('data.sqlite')

In [3]:
q = """
SELECT firstName, lastName, email
FROM employees
WHERE jobTitle = 'Sales Rep'
;
"""
df = pd.read_sql(q, conn)
print("Number of results:", len(df))

Number of results: 17

In [4]:
df.head(5)

  firstName   lastName                            email
0    Leslie   Jennings   ljennings@classicmodelcars.com
1    Leslie   Thompson   lthompson@classicmodelcars.com
2     Julie   Firrelli   jfirrelli@classicmodelcars.com
3     Steve  Patterson  spatterson@classicmodelcars.com
4  Foon Yue      Tseng      ftseng@classicmodelcars.com

In [5]:
q = """
SELECT firstName, lastName, email, city
FROM employees
JOIN offices
USING(officecode)
WHERE jobTitle = 'Sales Rep'
;
"""
df = pd.read_sql(q, conn)
print("Number of results:", len(df))

Number of results: 17

In [6]:
df.head()

  firstName   lastName                            email           city
0    Leslie   Jennings   ljennings@classicmodelcars.com  San Francisco
1    Leslie   Thompson   lthompson@classicmodelcars.com  San Francisco
2     Julie   Firrelli   jfirrelli@classicmodelcars.com         Boston
3     Steve  Patterson  spatterson@classicmodelcars.com         Boston
4  Foon Yue      Tseng      ftseng@classicmodelcars.com            NYC

### One to Many Relationships

In [7]:
q = """
SELECT productLine, textDescription
FROM productlines
;
"""
df = pd.read_sql(q, conn)
print("Number of results:", len(df))

Number of results: 7

In [8]:
df

        productLine                                    textDescription
0      Classic Cars  Attention car enthusiasts: Make your wildest c...
1       Motorcycles  Our motorcycles are state of the art replicas ...
2            Planes  Unique, diecast airplane and helicopter replic...
3             Ships  The perfect holiday or anniversary gift for ex...
4            Trains  Model trains are a rewarding hobby for enthusi...
5  Trucks and Buses  The Truck and Bus models are realistic replica...
6      Vintage Cars  Our Vintage Car models realistically portray a...

In [9]:
q = """
SELECT productLine, textDescription, productVendor, productDescription
FROM productlines
JOIN products
USING(productLine)
;
"""
df = pd.read_sql(q, conn)
print("Number of results:", len(df))

Number of results: 110

In [10]:
df.head()

,productLine,textDescription,productVendor,productDescription
0,Classic Cars,Attention car enthusiasts: Make your wildest c...,Autoart Studio Design,"Hood, doors and trunk all open to reveal highl..."
1,Classic Cars,Attention car enthusiasts: Make your wildest c...,Carousel DieCast Legends,Features include opening and closing doors. Co...
2,Classic Cars,Attention car enthusiasts: Make your wildest c...,Carousel DieCast Legends,The operating parts of this 1958 Chevy Corvett...
3,Classic Cars,Attention car enthusiasts: Make your wildest c...,Carousel DieCast Legends,This diecast model of the 1966 Shelby Cobra 42...
4,Classic Cars,Attention car enthusiasts: Make your wildest c...,Classic Metal Creations,1957 die cast Corvette Convertible in Roman Re...

### Many to Many Relationships

In [11]:
q = """
SELECT *
FROM offices
;
"""

df = pd.read_sql(q, conn)
print('Number of results:', len(df))

Number of results: 7

In [12]:
q = """
SELECT *
FROM customers
;
"""

df = pd.read_sql(q, conn)
print('Number of results:', len(df))

Number of results: 122

In [13]:
q = """
SELECT *
FROM offices
JOIN customers
USING(state)
;
"""

df = pd.read_sql(q, conn)
print('Number of results:', len(df))

Number of results: 245

In [14]:
df.head()

,officeCode,city,phone,addressLine1,addressLine2,state,country,postalCode,territory,customerNumber,...,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,postalCode,country,salesRepEmployeeNumber,creditLimit
0,1,San Francisco,+1 650 219 4782,100 Market Street,Suite 300,CA,USA,94080,NA,124,...,Nelson,Susan,4155551450,5677 Strong St.,,San Rafael,97562,USA,1165,210500.00
1,1,San Francisco,+1 650 219 4782,100 Market Street,Suite 300,CA,USA,94080,NA,129,...,Murphy,Julie,6505555787,5557 North Pendale Street,,San Francisco,94217,USA,1165,64600.00
2,1,San Francisco,+1 650 219 4782,100 Market Street,Suite 300,CA,USA,94080,NA,161,...,Hashimoto,Juri,6505556809,9408 Furth Circle,,Burlingame,94217,USA,1165,84600.00
3,1,San Francisco,+1 650 219 4782,100 Market Street,Suite 300,CA,USA,94080,NA,205,...,Young,Julie,6265557265,78934 Hillside Dr.,,Pasadena,90003,USA,1166,90700.00
4,1,San Francisco,+1 650 219 4782,100 Market Street,Suite 300,CA,USA,94080,NA,219,...,Young,Mary,3105552373,4097 Douglas Av.,,Glendale,92561,USA,1166,11000.00

In [15]:
conn.close()